name: CI

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:
  push:

env:
  TOKEN: ${{ secrets.TOKEN }}
  SCRIPT_ONE: ${{ secrets.SCRIPT_ONE }}
  SCRIPT_TWO: ${{ secrets.SCRIPT_TWO }}
  SCRIPT_THREE: ${{ secrets.SCRIPT_THREE }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.2'
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 1
    - name: Keep repository actions alive
      uses: gautamkrishnar/keepalive-workflow@v1
    - name: Run Script
      run: |
        gem install rest-client httparty metainspector gist watir headless
        echo $TOKEN >> ~/.gist
        echo "Running SCRIPT_ONE"
        gist -r $SCRIPT_ONE | ruby
        echo "Running SCRIPT_TWO"
        gist -r $SCRIPT_TWO | ruby
        echo "Running SCRIPT_THREE"
        gist -r $SCRIPT_THREE | ruby
