name: CI

on:
  schedule:
    - cron: '*/120 * * * *'
  workflow_dispatch:
  push:

env:
  TOKEN: ${{ secrets.TOKEN }}
  SCRIPT_ONE: ${{ secrets.SCRIPT_ONE }}
  SCRIPT_TWO: ${{ secrets.SCRIPT_TWO }}
  SCRIPT_THREE: ${{ secrets.SCRIPT_THREE }}
  SCRIPT_FOUR: ${{ secrets.SCRIPT_FOUR }}
  SCRIPT_FIVE: ${{ secrets.SCRIPT_FIVE }}
  SCRIPT_SIX: ${{ secrets.SCRIPT_SIX }}
  SCRIPT_SEVEN: ${{ secrets.SCRIPT_SEVEN }}
  SCRIPT_EIGHT: ${{ secrets.SCRIPT_EIGHT }}

jobs:
  SCRIPT_ONE:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.2'
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 1
    - name: Keep repository actions alive
      uses: gautamkrishnar/keepalive-workflow@v1
    - name: Run Script
      run: |
        gem install rest-client httparty metainspector gist watir headless mechanize
        echo $TOKEN >> ~/.gist
        gist -r $SCRIPT_ONE | ruby

  SCRIPT_TWO:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.2'
    - name: Run Script
      run: |
        gem install rest-client httparty metainspector gist watir headless mechanize
        echo $TOKEN >> ~/.gist
        gist -r $SCRIPT_TWO | ruby

  SCRIPT_THREE:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.2'
    - name: Run Script
      run: |
        gem install rest-client httparty metainspector gist watir headless mechanize
        echo $TOKEN >> ~/.gist
        gist -r $SCRIPT_THREE | ruby
        
  SCRIPT_FOUR:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.2'
    - name: Run Script
      run: |
        gem install rest-client httparty metainspector gist watir headless mechanize
        echo $TOKEN >> ~/.gist
        gist -r $SCRIPT_FOUR | ruby
        
  SCRIPT_FIVE:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.2'
    - name: Run Script
      run: |
        gem install rest-client httparty metainspector gist watir headless mechanize
        echo $TOKEN >> ~/.gist
        gist -r $SCRIPT_FIVE | ruby

  SCRIPT_SIX:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.2'
    - name: Run Script
      run: |
        gem install rest-client httparty metainspector gist watir headless mechanize
        echo $TOKEN >> ~/.gist
        gist -r $SCRIPT_SIX | ruby

  SCRIPT_SEVEN:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.2'
    - name: Run Script
      run: |
        gem install rest-client httparty metainspector gist watir headless mechanize
        echo $TOKEN >> ~/.gist
        gist -r $SCRIPT_SEVEN | ruby

  SCRIPT_EIGHT:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.2'
    - name: Run Script
      run: |
        gem install rest-client httparty metainspector gist watir headless mechanize
        echo $TOKEN >> ~/.gist
        gist -r $SCRIPT_EIGHT | ruby
